# Generated by Django 2.2.1 on 2019-05-27 17:52

import callyourmoms.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('index_page_content', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MemberDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('name', models.CharField(max_length=255)),
                ('intro', models.CharField(max_length=250)),
                ('content', wagtail.core.fields.StreamField([('full_richtext', callyourmoms.blocks.RichTextBlock())], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Member Page',
                'verbose_name_plural': 'Members',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MemberIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('index_page_content', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='YearTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('thumbnail_description', models.CharField(max_length=250)),
                ('week', models.CharField(blank=True, choices=[('undefined', 'UNDEFINED'), ('Week 1', 'WEEK-ONE'), ('Week 2', 'WEEK-TWO'), ('Week 3', 'WEEK-THREE'), ('Week 4', 'WEEK-FOUR'), ('Week 5', 'WEEK-FIVE'), ('Week 6', 'WEEK-SIX'), ('Week 7', 'WEEK-SEVEN'), ('Week 8', 'WEEK-EIGHT'), ('Week 9', 'WEEK-NINE'), ('Week 10', 'WEEK-TEN'), ('Week 11', 'WEEK-ELEVON'), ('Week 12', 'WEEK-TWELVE'), ('Week 13', 'WEEK-THIRTEEN'), ('Playoffs QuarterFinals', 'PLAYOFFS-QUARTERFINALS'), ('Playoffs SemiFinals', 'PLAYOFFS-SEMIFINALS'), ('Playoffs Championship', 'PLAYOFFS-CHAMPIONSHIP'), ('Pre-Season', 'PRE-SEASON'), ('Off-Season', 'OFF-SEASON'), ('Post-Season', 'POST-SEASON')], max_length=50, null=True)),
                ('content', wagtail.core.fields.StreamField([('full_richtext', callyourmoms.blocks.RichTextBlock())], blank=True, null=True)),
                ('thumbnail_image', models.ForeignKey(blank=True, help_text='thumb nail images will be rendered 100 x 100 px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='callyourmoms.YearTag')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
            bases=('wagtailcore.page',),
        ),
    ]
