# Generated by Django 2.2.1 on 2019-06-02 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('callyourmoms', '0002_auto_20190602_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastdetailpage',
            name='podcast_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
